[workspace]
resolver = "2"
members = [
    "crates/alkahest",
    "crates/alkahest-data",
    "crates/alkahest-panic-handler",
    "crates/alkahest-pm",
    "crates/d2tools",
    "crates/destiny-havok",
    "crates/egui-directx11",
]

[workspace.dependencies]
anyhow = { version = "1.0.71" }
binrw = "0.13.3"
destiny-pkg = "0.9.9"
egui = { version = "0.24.1", features = ["persistence"] }
glam = { version = "0.25", features = ["bytemuck", "mint"] }
itertools = "0.12.0"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
rustc-hash = "1.1.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.113"
serde_yaml = "0.9.25"
thiserror = "1"
tiger-parse = { version = "0.1.3", git = "https://github.com/v4nguard/tiger-parse", features = [
    "check_types",
    "destiny_pkg",
    "check_types_debug",
] }
windows = { version = "0.43.0", features = [
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_Graphics_Direct3D_Fxc",
] }


[profile.dev.package.destiny-pkg]
opt-level = 3

[profile.dev]
# opt-level = 3
# cohae: Overflow checks are nice for some, but not for us
overflow-checks = false
