[package]
name = "alkahest"
version = "0.1.0"
edition = "2021"
authors = ["cohaereo <cohaereo@protonmail.com>"]

[dependencies]
destiny-havok = { path = "./crates/destiny-havok" }
destiny-pkg = { version = "0.6.2", git = "https://github.com/v4nguard/destiny-pkg" }

anyhow = { version = "1.0.71" }
winit = { version = "0.28" }
binrw = "0.12"
itertools = "0.11.0"
ddsfile = "0.5.1"
hex = "0.4.3"
bytemuck = { version = "1.13.1", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

windows = { version = "0.43.0", features = [
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_Graphics_Direct3D_Fxc",
] }
raw-window-handle = "0.5.2"
u16cstr = "0.4.0"
glam = { version = "0.25", features = ["bytemuck", "mint"] }
nohash-hasher = "0.2.0"
fastrand = "2.0.0"

egui = { version = "0.22", features = ["persistence"] }
egui-winit = "0.22.0"
egui-directx11 = { path = "./crates/egui-directx11" }
tracing-tracy = "0.10.2"
tracy-client = "0.15.2"
bitflags = "2.3.3"
rayon = "1.7.0"
frustum_query = "0.1.2"
lazy_static = "1.4.0"
ringbuffer = "0.14.2"
serde = { version = "1.0.188", features = ["derive"] }
serde_yaml = "0.9.25"
parking_lot = "0.12.1"
strum = { version = "0.25.0", features = ["derive"] }
obj = "0.10.2"
bitfield-struct = "0.5.3"
genmesh = "0.6.2"
crossbeam = "0.8.2"
num-traits = "0.2.16"
num-derive = "0.4.0"
color-eyre = "0.6.2"
regex = "1.9.5"
clap = { version = "4.4.4", features = ["derive"] }
poll-promise = { version = "0.3.0", features = ["tokio"] }
tokio = { version = "1.32.0", features = ["rt", "macros"] }
thiserror = "1.0.49"
png = "0.17.10"
const_format = "0.2.31"
ron = "0.8.1"

# bevy_ecs = "0.11.3"
hecs = "0.10.3"
tinyvec = "1.6.0"
native-dialog = "0.7.0"
paste = "1.0.14"

discord-rpc-client = { version = "0.4.0", optional = true }

[features]
default = ["discord_rpc"]
tracy = []
# Ensures all TFX opcodes are interpreted
# TODO(cohae): Should this be a runtime configuration setting?
discord_rpc = ["dep:discord-rpc-client"]

debug_lock = []
# Disable sorting the map list
keep_map_order = []
tfx_strict_interpreter = []

[package.metadata.imgui-dx11-renderer]
targets = ["x86_64-pc-windows-gnu"]

[package.metadata.alkahest]
targets = ["x86_64-pc-windows-gnu"]

[profile.dev.package.destiny-pkg]
opt-level = 3

[profile.dev]
# opt-level = 3
# cohae: Overflow checks are nice for some, but not for us
overflow-checks = false
