[package]
name = "alkahest"
version = "0.1.0"
edition = "2021"
authors = ["cohaereo <cohaereo@protonmail.com>"]

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
destiny-pkg = { version = "0.4.1", git = "https://github.com/v4nguard/destiny-pkg" }
winit = { version = "0.27.2" }
binrw = "0.11"
itertools = "0.11.0"
ddsfile = "0.5.1"
hex = "0.4.3"
bytemuck = { version = "1.13.1", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

windows = { version = "0.43.0", features = [
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Foundation",
    "Win32_Graphics_Direct3D_Fxc",
] }
raw-window-handle = "0.5.2"
u16cstr = "0.4.0"
glam = { version = "0.24.1", features = ["bytemuck"] }
nohash-hasher = "0.2.0"
fastrand = "2.0.0"

imgui = "0.11.0"
imgui-dx11-renderer = { git = "https://github.com/cohaereo/imgui-dx11-renderer" }
imgui-winit-support = "0.11.0"
tracing-tracy = "0.10.2"
tracy-client = "0.15.2"
bitflags = "2.3.3"
rayon = "1.7.0"
frustum_query = "0.1.2"
lazy_static = "1.4.0"
ringbuffer = "0.14.2"
serde = { version = "1.0.183", features = ["derive"] }
serde_yaml = "0.9.25"

[features]
default = []
tracy = []

[package.metadata.imgui-dx11-renderer]
targets = ["x86_64-pc-windows-gnu"]

[package.metadata.alkahest]
targets = ["x86_64-pc-windows-gnu"]

[profile.dev.package.destiny-pkg]
opt-level = 3
