name: Build (nightly)

on:
  push:
    branches: [ "main", "lightfall" ]
    paths-ignore:
      - "**/.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Nightly (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        platform: [ windows-latest ]
        toolchain: [ stable ]
    steps:
      - uses: actions/checkout@v4

      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rust-build"

      #      - name: Install cargo-edit
      #        run: cargo install cargo-edit --force

      - name: Add nightly version metadata
        run:
          ./.github/cargo-set-version.exe set-version --package alkahest --metadata "nightly.$(date +'%Y%m%d%H%M')"

      - name: Build
        run: cargo build --verbose --release

      - name: Publish artifact
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: alkahest
          path: |
            ./target/release/*.exe
            ./target/release/*.pdb