name: Check

on:
  pull_request:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Check (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo check --release
